services:
  - type: web
    name: ecommerce-full
    env: node
    plan: free
    rootDir: ecommerce-backend
    buildCommand: |
      rm -rf ../ecommerce/node_modules ../ecommerce/package-lock.json
      cd ../ecommerce
      npm cache clean --force
      npm install --no-optional
      npm run build
      mv dist ../ecommerce-backend
      cd ../ecommerce-backend
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 25.1.0
